spring:
  application:
    name: employee-manager

  server:
    port: 8100

  datasource:
    url: jdbc:h2:mem:datab
    username: root
    password: pass
    driver-class-name: org.h2.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2


